### ISSUE TITLE
Typescript types not available

### ISSUE THREAD

**Issue by FilipChalupa** [noamr/use-view-transitions#6]
Maybe because https://github.com/noamr/use-view-transitions/commit/61f31b7d8e46aa32d218dab1c2eca4a2a81bb2dd is not released yet.

**Comment by noamr** [comment]
I released it now (sorry, was off-grid for a while).

**Comment by FilipChalupa** [comment]
I'm not sure it works properly. Npmjs.org still shows no [TS] badge and neither can I get types to work in my project.

@vkuprin there should be `"types": "…"` in `package.json` which is missing, right?


#### No badge

![image](https://github.com/noamr/use-view-transitions/assets/1045362/77b936b0-2b3c-4fb8-8a10-1541376b7558)

#### Other repository with the badge

![image](https://github.com/noamr/use-view-transitions/assets/1045362/2121b117-eeba-4beb-ab3e-56f34de1a964)

**Comment by vkuprin** [comment]
@FilipChalupa The cleaner approach would be to rewrite everything in types and eliminate .js files altogether. Relying on declaration files can lead to some problems with package types, as we've seen. I will make a patch soon to cover everything in TypeScript. Please bear with me

**Comment by vkuprin** [comment]
@FilipChalupa @noamr Please take a look at my patch https://github.com/noamr/use-view-transitions/pull/7
With `npm run build:packages` it should create a dist folder with .js files

**Comment by FilipChalupa** [comment]
@vkuprin thank you for your quick response. 🙂 I'm worried that the changes will complicate use without TypeScript. May I suggest an edit? Something like this: https://github.com/vkuprin/use-view-transitions/pull/1. It's not perfect. I've been forced to place a few `@ts-ignore` and I'm not completely sure that types will be picked up from `exports.*.types` but I believe it is a step in right direction. 🤷‍♀️

**Comment by vkuprin** [comment]
@FilipChalupa Merged your changes! Good point. It's not perfect, but we are gradually improving our hook. Adding test coverage with something like Jest could potentially be our next steps

**Comment by vkuprin** [comment]
@noamr The last CI pipe has failed. Please redeploy or let's push to the master .lock files to avoid pipeline failures. Right now, it's an old version

<img width="608" alt="Screenshot 2023-08-21 at 12 08 14" src="https://github.com/noamr/use-view-transitions/assets/51091179/b5b67f68-53f2-4168-91ed-fbe6cc3a9eb7">

**Comment by williamisnotdefined** [comment]
Meanwhile I have created a .d.ts with the following statement:
declare module "use-view-transitions/next";

it made the vscode stop complaining about the library installation, hope it work for you guys
